# Generated by Django 5.1.3 on 2025-07-13 04:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Hobby',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='LearningStyle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('description', models.TextField()),
                ('goal', models.CharField(max_length=255)),
                ('expectation', models.CharField(default='-', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='TemplateAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_questions', models.PositiveSmallIntegerField()),
                ('max_grade', models.FloatField(default=20.0)),
            ],
        ),
        migrations.CreateModel(
            name='TypeQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('format', models.CharField(max_length=50)),
                ('location', models.FileField(default='-', upload_to='Media/')),
                ('related_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Api.lesson')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('code', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('year', models.PositiveSmallIntegerField()),
                ('cycle', models.PositiveSmallIntegerField()),
                ('career', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Api.school')),
                ('learning_style', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Api.learningstyle')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AdaptedSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('completed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField()),
                ('image', models.ImageField(null=True, upload_to='Media/')),
                ('related_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Api.lesson')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Api.student')),
            ],
        ),
        migrations.CreateModel(
            name='AdaptedRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('completed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField()),
                ('image', models.ImageField(null=True, upload_to='Media/')),
                ('related_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Api.lesson')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Api.student')),
            ],
        ),
        migrations.CreateModel(
            name='AdaptedActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('completed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField()),
                ('image', models.ImageField(null=True, upload_to='Media/')),
                ('related_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Api.lesson')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Api.student')),
            ],
        ),
        migrations.CreateModel(
            name='StudentHobby',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hobby', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Api.hobby')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Api.student')),
            ],
            options={
                'verbose_name': 'Student Hobby',
                'unique_together': {('student', 'hobby')},
            },
        ),
        migrations.AddField(
            model_name='student',
            name='hobbies',
            field=models.ManyToManyField(related_name='student', through='Api.StudentHobby', to='Api.hobby'),
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('description', models.TextField()),
                ('year', models.PositiveSmallIntegerField()),
                ('ciclo', models.PositiveSmallIntegerField()),
                ('image', models.ImageField(null=True, upload_to='Media/')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Api.school')),
            ],
        ),
        migrations.CreateModel(
            name='StudentSubject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.FloatField(default=0.0)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Api.student')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Api.subject')),
            ],
            options={
                'verbose_name': 'Student Subject',
                'unique_together': {('student', 'subject')},
            },
        ),
        migrations.AddField(
            model_name='student',
            name='enrollments',
            field=models.ManyToManyField(related_name='student', through='Api.StudentSubject', to='Api.subject'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Api.subject'),
        ),
        migrations.CreateModel(
            name='AdaptedQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('options', models.TextField(null=True)),
                ('answer', models.TextField(blank=True, null=True)),
                ('status', models.BooleanField(default=False)),
                ('completed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField()),
                ('related_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Api.lesson')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Api.student')),
                ('template', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Api.templateassessment')),
            ],
        ),
        migrations.AddField(
            model_name='templateassessment',
            name='type_questions',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Api.typequestion'),
        ),
    ]
