# Generated by Django 5.1.3 on 2025-07-13 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adaptedactivity',
            name='image',
            field=models.ImageField(null=True, upload_to='Subjec/'),
        ),
        migrations.AlterField(
            model_name='adaptedrecommendation',
            name='image',
            field=models.ImageField(null=True, upload_to='Subjec/'),
        ),
        migrations.AlterField(
            model_name='adaptedsummary',
            name='image',
            field=models.ImageField(null=True, upload_to='Subjec/'),
        ),
        migrations.AlterField(
            model_name='content',
            name='location',
            field=models.FileField(default='-', upload_to='Content/'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='image',
            field=models.ImageField(null=True, upload_to='Subject/'),
        ),
    ]
