# Generated by Django 5.1.3 on 2025-07-13 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0002_alter_adaptedactivity_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adaptedactivity',
            name='image',
            field=models.ImageField(null=True, upload_to='Recomendation/'),
        ),
        migrations.AlterField(
            model_name='adaptedrecommendation',
            name='image',
            field=models.ImageField(null=True, upload_to='Recomendation/'),
        ),
        migrations.AlterField(
            model_name='adaptedsummary',
            name='image',
            field=models.ImageField(null=True, upload_to='Recomendation/'),
        ),
    ]
